import type { HeritageEvent } from "@/lib/events/types"

export const heritageEventsSeed: HeritageEvent[] = [
  // Gujarat
  {
    id: "e-raniki-vav-heritage-walks",
    name: "Heritage Walks",
    description: "Weekly guided heritage walks around Rani ki Vav and nearby historic lanes.",
    state: "Gujarat",
    placeId: "g1",
    placeName: "Rani ki Vav",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "weekly",
    daysOfWeek: [0],
  },
  {
    id: "e-raniki-vav-world-heritage-day",
    name: "World Heritage Day Special Event",
    description: "Special guided tours and cultural programs to celebrate World Heritage Day.",
    state: "Gujarat",
    placeId: "g1",
    placeName: "Rani ki Vav",
    startDate: "2026-04-18",
    recurrence: "single",
  },
  {
    id: "e-modhera-dance-performances",
    name: "Cultural Dance Performances",
    description: "Weekend cultural dance performances at the Modhera Sun Temple precincts (seasonal).",
    state: "Gujarat",
    placeId: "g7",
    placeName: "Modhera Sun Temple",
    startDate: "2026-03-01",
    endDate: "2026-04-30",
    recurrence: "weekend",
  },
  {
    id: "e-modhera-evening-light-show",
    name: "Evening Light Show",
    description: "Daily evening light and sound experience highlighting temple history and architecture.",
    state: "Gujarat",
    placeId: "g7",
    placeName: "Modhera Sun Temple",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "daily",
  },
  {
    id: "e-somnath-aarti-laser-show",
    name: "Daily Aarti & Laser Show",
    description: "Daily temple aarti and evening laser show (timings vary by season).",
    state: "Gujarat",
    placeId: "g5",
    placeName: "Somnath Temple",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "daily",
  },
  {
    id: "e-somnath-mahashivratri",
    name: "Mahashivratri Festival",
    description: "Festival day at Somnath with special rituals and large crowds. (Verify exact date for the year.)",
    state: "Gujarat",
    placeId: "g5",
    placeName: "Somnath Temple",
    startDate: "2026-03-08",
    recurrence: "single",
    isFestival: true,
    festivalKey: "mahashivratri",
  },
  {
    id: "e-somnath-ram-navami",
    name: "Ram Navami Celebrations",
    description: "Festival celebrations at Somnath. (Verify exact date for the year.)",
    state: "Gujarat",
    placeId: "g5",
    placeName: "Somnath Temple",
    startDate: "2026-04-05",
    recurrence: "single",
    isFestival: true,
    festivalKey: "ram_navami",
  },
  {
    id: "e-dwarka-aarti-rituals",
    name: "Temple Aarti & Rituals",
    description: "Daily aarti and rituals at Dwarkadhish Temple.",
    state: "Gujarat",
    placeId: "g6",
    placeName: "Dwarkadhish Temple",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "daily",
  },
  {
    id: "e-dwarka-ram-navami",
    name: "Ram Navami Festival",
    description: "Ram Navami festival celebrations at Dwarkadhish Temple. (Verify exact date for the year.)",
    state: "Gujarat",
    placeId: "g6",
    placeName: "Dwarkadhish Temple",
    startDate: "2026-04-05",
    recurrence: "single",
    isFestival: true,
    festivalKey: "ram_navami",
  },
  {
    id: "e-dwarka-summer-pilgrimage-rush",
    name: "Summer Pilgrimage Rush",
    description: "Peak summer pilgrimage season; expect higher footfall and longer queues.",
    state: "Gujarat",
    placeId: "g6",
    placeName: "Dwarkadhish Temple",
    startDate: "2026-05-01",
    endDate: "2026-06-30",
    recurrence: "range",
  },
  {
    id: "e-adalaj-ahmedabad-heritage-walk",
    name: "Ahmedabad Heritage Walk",
    description: "Weekend heritage walks including Adalaj Stepwell. Organized by Ahmedabad Municipal Corporation.",
    state: "Gujarat",
    placeId: "g8",
    placeName: "Adalaj Stepwell",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "weekend",
    organizer: "Ahmedabad Municipal Corporation",
  },
  {
    id: "e-lothal-museum-archaeological-tours",
    name: "Museum & Archaeological Tours",
    description: "Daily museum visits and guided archaeological site tours.",
    state: "Gujarat",
    placeId: "g4",
    placeName: "Lothal",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "daily",
  },
  {
    id: "e-lothal-educational-visits-peak",
    name: "Educational Visits Peak",
    description: "Peak season for school and college educational visits (April–May).",
    state: "Gujarat",
    placeId: "g4",
    placeName: "Lothal",
    startDate: "2026-04-01",
    endDate: "2026-05-31",
    recurrence: "range",
  },
  {
    id: "e-dholavira-desert-cultural-experience",
    name: "Desert Cultural Experience",
    description: "Best time for a desert cultural experience around Dholavira (pleasant weather).",
    state: "Gujarat",
    placeId: "g3",
    placeName: "Dholavira",
    startDate: "2026-03-01",
    endDate: "2026-03-31",
    recurrence: "range",
  },
  {
    id: "e-dholavira-limited-visits-heat-season",
    name: "Limited Visits (Heat Season)",
    description: "Limited visits recommended due to heat; plan early mornings and hydration.",
    state: "Gujarat",
    placeId: "g3",
    placeName: "Dholavira",
    startDate: "2026-05-01",
    endDate: "2026-06-30",
    recurrence: "range",
  },
  {
    id: "e-laxmi-vilas-palace-royal-tour",
    name: "Royal Palace Tour",
    description: "Daily palace tour showcasing royal collections and Indo-Saracenic architecture.",
    state: "Gujarat",
    placeId: "g9",
    placeName: "Laxmi Vilas Palace",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "daily",
  },
  {
    id: "e-uparkot-fort-exploration-tours",
    name: "Fort Exploration Tours",
    description: "Explore Uparkot Fort’s bastions, caves, and stepwells with local guides.",
    state: "Gujarat",
    placeId: "g10",
    placeName: "Uparkot Fort",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "range",
  },
  {
    id: "e-champaner-trekking-heritage-visit",
    name: "Trekking + Heritage Visit",
    description: "Best season for trekking and heritage exploration around Champaner–Pavagadh.",
    state: "Gujarat",
    placeId: "g2",
    placeName: "Champaner-Pavagadh Archaeological Park",
    startDate: "2026-03-01",
    endDate: "2026-04-30",
    recurrence: "range",
  },
  {
    id: "e-champaner-pilgrimage-visits",
    name: "Pilgrimage Visits",
    description: "Pilgrimage visits continue into early summer; plan for warmer afternoons.",
    state: "Gujarat",
    placeId: "g2",
    placeName: "Champaner-Pavagadh Archaeological Park",
    startDate: "2026-05-01",
    endDate: "2026-06-30",
    recurrence: "range",
  },

  // Rajasthan
  {
    id: "e-amber-light-sound-show",
    name: "Light & Sound Show",
    description: "Daily light and sound show at Amber Fort (evenings).",
    state: "Rajasthan",
    placeId: "r1",
    placeName: "Amber Fort",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "daily",
  },
  {
    id: "e-hawa-mahal-city-heritage-walk",
    name: "City Heritage Walk",
    description: "Guided city heritage walk covering Hawa Mahal and the old city.",
    state: "Rajasthan",
    placeId: "r2",
    placeName: "Hawa Mahal",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "weekend",
  },
  {
    id: "e-city-palace-museum-tours",
    name: "Museum Tours & Cultural Displays",
    description: "Daily museum tours and cultural displays at City Palace Jaipur.",
    state: "Rajasthan",
    placeId: "r3",
    placeName: "City Palace Jaipur",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "daily",
  },
  {
    id: "e-jantar-mantar-astronomy-guided-tours",
    name: "Astronomy Guided Tours",
    description: "Guided astronomy tours explaining the historic instruments at Jantar Mantar.",
    state: "Rajasthan",
    placeId: "r4",
    placeName: "Jantar Mantar Jaipur",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "daily",
  },
  {
    id: "e-chittorgarh-light-sound-show",
    name: "Light & Sound Show",
    description: "Evening light and sound show at Chittorgarh Fort.",
    state: "Rajasthan",
    placeId: "r5",
    placeName: "Chittorgarh Fort",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "daily",
  },
  {
    id: "e-mehrangarh-folk-music-programs",
    name: "Rajasthan Folk Music Programs",
    description: "Seasonal folk music programs (March–April).",
    state: "Rajasthan",
    placeId: "r6",
    placeName: "Mehrangarh Fort",
    startDate: "2026-03-01",
    endDate: "2026-04-30",
    recurrence: "weekend",
  },
  {
    id: "e-jaisalmer-desert-cultural-activities-peak",
    name: "Desert Cultural Activities (Peak Season)",
    description: "Peak season desert cultural activities around Jaisalmer.",
    state: "Rajasthan",
    placeId: "r7",
    placeName: "Jaisalmer Fort",
    startDate: "2026-03-01",
    endDate: "2026-03-31",
    recurrence: "range",
  },
  {
    id: "e-jaisalmer-reduced-activity-heat",
    name: "Reduced Activities (Heat Season)",
    description: "Reduced desert activity in May–June due to heat; plan sunrise/sunset slots.",
    state: "Rajasthan",
    placeId: "r7",
    placeName: "Jaisalmer Fort",
    startDate: "2026-05-01",
    endDate: "2026-06-30",
    recurrence: "range",
  },
  {
    id: "e-kumbhalgarh-light-sound-show",
    name: "Light & Sound Show",
    description: "Evening light and sound show at Kumbhalgarh Fort.",
    state: "Rajasthan",
    placeId: "r8",
    placeName: "Kumbhalgarh Fort",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "daily",
  },
  {
    id: "e-lake-palace-cultural-evenings",
    name: "Lake View Cultural Evenings",
    description: "Cultural evenings with lake views (schedule depends on venue access).",
    state: "Rajasthan",
    placeId: "r9",
    placeName: "Lake Palace",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "daily",
  },
  {
    id: "e-dilwara-spiritual-visits-guided-tours",
    name: "Spiritual Visits & Guided Tours",
    description: "Daily spiritual visits and guided tours at Dilwara Temples.",
    state: "Rajasthan",
    placeId: "r10",
    placeName: "Dilwara Temples",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    recurrence: "daily",
  },
]
