<?php

namespace Database\Seeders;

use App\Models\Event;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        $events = [
            // Gujarat
            [
                'id' => 'e-raniki-vav-heritage-walks',
                'name' => 'Heritage Walks',
                'description' => 'Weekly guided heritage walks around Rani ki Vav and nearby historic lanes.',
                'state' => 'Gujarat',
                'place_id' => 'g1',
                'place_name' => 'Rani ki Vav',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'weekly',
                'days_of_week' => [0],
                'is_festival' => false,
            ],
            [
                'id' => 'e-raniki-vav-world-heritage-day',
                'name' => 'World Heritage Day Special Event',
                'description' => 'Special guided tours and cultural programs to celebrate World Heritage Day.',
                'state' => 'Gujarat',
                'place_id' => 'g1',
                'place_name' => 'Rani ki Vav',
                'start_date' => '2026-04-18',
                'recurrence' => 'single',
                'is_festival' => false,
            ],
            [
                'id' => 'e-modhera-dance-performances',
                'name' => 'Cultural Dance Performances',
                'description' => 'Weekend cultural dance performances at the Modhera Sun Temple precincts (seasonal).',
                'state' => 'Gujarat',
                'place_id' => 'g7',
                'place_name' => 'Modhera Sun Temple',
                'start_date' => '2026-03-01',
                'end_date' => '2026-04-30',
                'recurrence' => 'weekend',
                'is_festival' => false,
            ],
            [
                'id' => 'e-modhera-evening-light-show',
                'name' => 'Evening Light Show',
                'description' => 'Daily evening light and sound experience highlighting temple history and architecture.',
                'state' => 'Gujarat',
                'place_id' => 'g7',
                'place_name' => 'Modhera Sun Temple',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'daily',
                'is_festival' => false,
            ],
            [
                'id' => 'e-somnath-aarti-laser-show',
                'name' => 'Daily Aarti & Laser Show',
                'description' => 'Daily temple aarti and evening laser show (timings vary by season).',
                'state' => 'Gujarat',
                'place_id' => 'g5',
                'place_name' => 'Somnath Temple',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'daily',
                'is_festival' => false,
            ],
            [
                'id' => 'e-somnath-mahashivratri',
                'name' => 'Mahashivratri Festival',
                'description' => 'Festival day at Somnath with special rituals and large crowds. (Verify exact date for the year.)',
                'state' => 'Gujarat',
                'place_id' => 'g5',
                'place_name' => 'Somnath Temple',
                'start_date' => '2026-03-08',
                'recurrence' => 'single',
                'is_festival' => true,
                'festival_key' => 'mahashivratri',
            ],
            [
                'id' => 'e-somnath-ram-navami',
                'name' => 'Ram Navami Celebrations',
                'description' => 'Festival celebrations at Somnath. (Verify exact date for the year.)',
                'state' => 'Gujarat',
                'place_id' => 'g5',
                'place_name' => 'Somnath Temple',
                'start_date' => '2026-04-05',
                'recurrence' => 'single',
                'is_festival' => true,
                'festival_key' => 'ram_navami',
            ],
            [
                'id' => 'e-dwarka-aarti-rituals',
                'name' => 'Temple Aarti & Rituals',
                'description' => 'Daily aarti and rituals at Dwarkadhish Temple.',
                'state' => 'Gujarat',
                'place_id' => 'g6',
                'place_name' => 'Dwarkadhish Temple',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'daily',
                'is_festival' => false,
            ],
            [
                'id' => 'e-dwarka-ram-navami',
                'name' => 'Ram Navami Festival',
                'description' => 'Ram Navami festival celebrations at Dwarkadhish Temple. (Verify exact date for the year.)',
                'state' => 'Gujarat',
                'place_id' => 'g6',
                'place_name' => 'Dwarkadhish Temple',
                'start_date' => '2026-04-05',
                'recurrence' => 'single',
                'is_festival' => true,
                'festival_key' => 'ram_navami',
            ],
            [
                'id' => 'e-dwarka-summer-pilgrimage-rush',
                'name' => 'Summer Pilgrimage Rush',
                'description' => 'Peak summer pilgrimage season; expect higher footfall and longer queues.',
                'state' => 'Gujarat',
                'place_id' => 'g6',
                'place_name' => 'Dwarkadhish Temple',
                'start_date' => '2026-05-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'range',
                'is_festival' => false,
            ],
            [
                'id' => 'e-adalaj-ahmedabad-heritage-walk',
                'name' => 'Ahmedabad Heritage Walk',
                'description' => 'Weekend heritage walks including Adalaj Stepwell. Organized by Ahmedabad Municipal Corporation.',
                'state' => 'Gujarat',
                'place_id' => 'g8',
                'place_name' => 'Adalaj Stepwell',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'weekend',
                'organizer' => 'Ahmedabad Municipal Corporation',
                'is_festival' => false,
            ],
            [
                'id' => 'e-lothal-museum-archaeological-tours',
                'name' => 'Museum & Archaeological Tours',
                'description' => 'Daily museum visits and guided archaeological site tours.',
                'state' => 'Gujarat',
                'place_id' => 'g4',
                'place_name' => 'Lothal',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'daily',
                'is_festival' => false,
            ],
            [
                'id' => 'e-lothal-educational-visits-peak',
                'name' => 'Educational Visits Peak',
                'description' => 'Peak season for school and college educational visits (April–May).',
                'state' => 'Gujarat',
                'place_id' => 'g4',
                'place_name' => 'Lothal',
                'start_date' => '2026-04-01',
                'end_date' => '2026-05-31',
                'recurrence' => 'range',
                'is_festival' => false,
            ],
            [
                'id' => 'e-dholavira-desert-cultural-experience',
                'name' => 'Desert Cultural Experience',
                'description' => 'Best time for a desert cultural experience around Dholavira (pleasant weather).',
                'state' => 'Gujarat',
                'place_id' => 'g3',
                'place_name' => 'Dholavira',
                'start_date' => '2026-03-01',
                'end_date' => '2026-03-31',
                'recurrence' => 'range',
                'is_festival' => false,
            ],
            [
                'id' => 'e-dholavira-limited-visits-heat-season',
                'name' => 'Limited Visits (Heat Season)',
                'description' => 'Limited visits recommended due to heat; plan early mornings and hydration.',
                'state' => 'Gujarat',
                'place_id' => 'g3',
                'place_name' => 'Dholavira',
                'start_date' => '2026-05-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'range',
                'is_festival' => false,
            ],
            [
                'id' => 'e-laxmi-vilas-palace-royal-tour',
                'name' => 'Royal Palace Tour',
                'description' => 'Daily palace tour showcasing royal collections and Indo-Saracenic architecture.',
                'state' => 'Gujarat',
                'place_id' => 'g9',
                'place_name' => 'Laxmi Vilas Palace',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'daily',
                'is_festival' => false,
            ],
            [
                'id' => 'e-uparkot-fort-exploration-tours',
                'name' => 'Fort Exploration Tours',
                'description' => 'Explore Uparkot Fort’s bastions, caves, and stepwells with local guides.',
                'state' => 'Gujarat',
                'place_id' => 'g10',
                'place_name' => 'Uparkot Fort',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'range',
                'is_festival' => false,
            ],
            [
                'id' => 'e-champaner-trekking-heritage-visit',
                'name' => 'Trekking + Heritage Visit',
                'description' => 'Best season for trekking and heritage exploration around Champaner–Pavagadh.',
                'state' => 'Gujarat',
                'place_id' => 'g2',
                'place_name' => 'Champaner-Pavagadh Archaeological Park',
                'start_date' => '2026-03-01',
                'end_date' => '2026-04-30',
                'recurrence' => 'range',
                'is_festival' => false,
            ],
            [
                'id' => 'e-champaner-pilgrimage-visits',
                'name' => 'Pilgrimage Visits',
                'description' => 'Pilgrimage visits continue into early summer; plan for warmer afternoons.',
                'state' => 'Gujarat',
                'place_id' => 'g2',
                'place_name' => 'Champaner-Pavagadh Archaeological Park',
                'start_date' => '2026-05-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'range',
                'is_festival' => false,
            ],

            // Rajasthan
            [
                'id' => 'e-amber-light-sound-show',
                'name' => 'Light & Sound Show',
                'description' => 'Daily light and sound show at Amber Fort (evenings).',
                'state' => 'Rajasthan',
                'place_id' => 'r1',
                'place_name' => 'Amber Fort',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'daily',
                'is_festival' => false,
            ],
            [
                'id' => 'e-hawa-mahal-city-heritage-walk',
                'name' => 'City Heritage Walk',
                'description' => 'Guided city heritage walk covering Hawa Mahal and the old city.',
                'state' => 'Rajasthan',
                'place_id' => 'r2',
                'place_name' => 'Hawa Mahal',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'weekend',
                'is_festival' => false,
            ],
            [
                'id' => 'e-city-palace-museum-tours',
                'name' => 'Museum Tours & Cultural Displays',
                'description' => 'Daily museum tours and cultural displays at City Palace Jaipur.',
                'state' => 'Rajasthan',
                'place_id' => 'r3',
                'place_name' => 'City Palace Jaipur',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'daily',
                'is_festival' => false,
            ],
            [
                'id' => 'e-jantar-mantar-astronomy-guided-tours',
                'name' => 'Astronomy Guided Tours',
                'description' => 'Guided astronomy tours explaining the historic instruments at Jantar Mantar.',
                'state' => 'Rajasthan',
                'place_id' => 'r4',
                'place_name' => 'Jantar Mantar Jaipur',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'daily',
                'is_festival' => false,
            ],
            [
                'id' => 'e-chittorgarh-light-sound-show',
                'name' => 'Light & Sound Show',
                'description' => 'Evening light and sound show at Chittorgarh Fort.',
                'state' => 'Rajasthan',
                'place_id' => 'r5',
                'place_name' => 'Chittorgarh Fort',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'daily',
                'is_festival' => false,
            ],
            [
                'id' => 'e-mehrangarh-folk-music-programs',
                'name' => 'Rajasthan Folk Music Programs',
                'description' => 'Seasonal folk music programs (March–April).',
                'state' => 'Rajasthan',
                'place_id' => 'r6',
                'place_name' => 'Mehrangarh Fort',
                'start_date' => '2026-03-01',
                'end_date' => '2026-04-30',
                'recurrence' => 'weekend',
                'is_festival' => false,
            ],
            [
                'id' => 'e-jaisalmer-desert-cultural-activities-peak',
                'name' => 'Desert Cultural Activities (Peak Season)',
                'description' => 'Peak season desert cultural activities around Jaisalmer.',
                'state' => 'Rajasthan',
                'place_id' => 'r7',
                'place_name' => 'Jaisalmer Fort',
                'start_date' => '2026-03-01',
                'end_date' => '2026-03-31',
                'recurrence' => 'range',
                'is_festival' => false,
            ],
            [
                'id' => 'e-jaisalmer-reduced-activity-heat',
                'name' => 'Reduced Activities (Heat Season)',
                'description' => 'Reduced desert activity in May–June due to heat; plan sunrise/sunset slots.',
                'state' => 'Rajasthan',
                'place_id' => 'r7',
                'place_name' => 'Jaisalmer Fort',
                'start_date' => '2026-05-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'range',
                'is_festival' => false,
            ],
            [
                'id' => 'e-kumbhalgarh-light-sound-show',
                'name' => 'Light & Sound Show',
                'description' => 'Evening light and sound show at Kumbhalgarh Fort.',
                'state' => 'Rajasthan',
                'place_id' => 'r8',
                'place_name' => 'Kumbhalgarh Fort',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'daily',
                'is_festival' => false,
            ],
            [
                'id' => 'e-lake-palace-cultural-evenings',
                'name' => 'Lake View Cultural Evenings',
                'description' => 'Cultural evenings with lake views (schedule depends on venue access).',
                'state' => 'Rajasthan',
                'place_id' => 'r9',
                'place_name' => 'Lake Palace',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'daily',
                'is_festival' => false,
            ],
            [
                'id' => 'e-dilwara-spiritual-visits-guided-tours',
                'name' => 'Spiritual Visits & Guided Tours',
                'description' => 'Daily spiritual visits and guided tours at Dilwara Temples.',
                'state' => 'Rajasthan',
                'place_id' => 'r10',
                'place_name' => 'Dilwara Temples',
                'start_date' => '2026-03-01',
                'end_date' => '2026-06-30',
                'recurrence' => 'daily',
                'is_festival' => false,
            ],
        ];

        foreach ($events as $event) {
            Event::updateOrCreate(['id' => $event['id']], $event);
        }
    }
}
